name: Sync Submodules

# run workflow manually
on:
  workflow_dispatch:

# Allow this job to clone and commit content to the repository
permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository using git
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Start sync according to chatgpt
        run: git submodule sync
      - name: Initialize submodule
        run: git submodule init
      - name: Pull submodules test
        run: git pull --recurse-submodules
      - name: Update submodule
        run: git submodule update --init
      - name: Test status
        run: git submodule status
      - name: Update submodule remote
        run: git submodule update --init --remote
      - name: Test Status Again
        run: git submodule status
        # git submodule update --init
        # git submodule update --recursive --remote
      #- name: Commit Changes
      #  run: |
      #    git add .
      #    git commit -m "Github Action Submodule Update `date +'%Y-%m-%d'`"
      #    git push
